name = "ScreamTask"
uuid = "b2510684-a651-4830-9843-2dd7a5f893e0"
version = "0.1.0"
authors = ["Quentin Dercon <quentindercon@gmail.com>"]

[deps]
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
NOMAD = "02130f1c-4665-5b79-af82-ff1385104aa0"
PRIMA = "0a7d04aa-8ac2-47b3-b7a7-9dbd6ad661ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
BlackBoxOptim = "0.6.3"
NOMAD = "2.4.2"
ProgressLogging = "0.1.6"
